backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { label: "Title (English)", name: "title_en", widget: "string" }
          - { label: "Title (Hebrew)", name: "title_he", widget: "string" }
          - { label: "Subtitle (English)", name: "subtitle_en", widget: "string" }
          - { label: "Subtitle (Hebrew)", name: "subtitle_he", widget: "string" }
          - { label: "Description Text (English)", name: "description_en", widget: "text" }
          - { label: "Description Text (Hebrew)", name: "description_he", widget: "text" }
      - name: "about"
        label: "About Page"
        file: "content/about.md"
        fields:
          - { label: "Title (English)", name: "title_en", widget: "string" }
          - { label: "Title (Hebrew)", name: "title_he", widget: "string" }
          - { label: "Description (English)", name: "description_en", widget: "string" }
          - { label: "Description (Hebrew)", name: "description_he", widget: "string" }
          - { label: "Background Title (English)", name: "backgroundTitle_en", widget: "string", default: "Professional Background" }
          - { label: "Background Title (Hebrew)", name: "backgroundTitle_he", widget: "string", default: "רקע מקצועי" }
          - { label: "Main Paragraph (English)", name: "mainParagraph_en", widget: "text" }
          - { label: "Main Paragraph (Hebrew)", name: "mainParagraph_he", widget: "text" }
          - { label: "Portrait Image", name: "portraitImage", widget: "image", default: "/lawyer-portrait.jpg" }
          - { label: "Portrait Alt Text (English)", name: "portraitAlt_en", widget: "string", default: "Revital Amir - Professional Attorney" }
          - { label: "Portrait Alt Text (Hebrew)", name: "portraitAlt_he", widget: "string", default: "רויטל אמיר - עורכת דין מקצועית" }
          - { label: "Education & Experience Section Title (English)", name: "educationSectionTitle_en", widget: "string", default: "Education & Experience" }
          - { label: "Education & Experience Section Title (Hebrew)", name: "educationSectionTitle_he", widget: "string", default: "השכלה וניסיון" }
          - label: "Education"
            name: "education"
            widget: "object"
            fields:
              - { label: "Section Title (English)", name: "title_en", widget: "string", default: "Education" }
              - { label: "Section Title (Hebrew)", name: "title_he", widget: "string", default: "השכלה" }
              - label: "Degrees"
                name: "degrees"
                widget: "list"
                fields:
                  - { label: "Degree (English)", name: "degree_en", widget: "string" }
                  - { label: "Degree (Hebrew)", name: "degree_he", widget: "string" }
                  - { label: "Institution (English)", name: "institution_en", widget: "string" }
                  - { label: "Institution (Hebrew)", name: "institution_he", widget: "string" }
                  - { label: "Year", name: "year", widget: "string" }
          - label: "Professional Experience"
            name: "experience"
            widget: "object"
            fields:
              - { label: "Section Title (English)", name: "title_en", widget: "string", default: "Professional Experience" }
              - { label: "Section Title (Hebrew)", name: "title_he", widget: "string", default: "ניסיון מקצועי" }
              - label: "Areas of Practice"
                name: "areasOfPractice"
                widget: "object"
                fields:
                  - { label: "Title (English)", name: "title_en", widget: "string", default: "Areas of Practice" }
                  - { label: "Title (Hebrew)", name: "title_he", widget: "string", default: "תחומי עיסוק" }
                  - label: "Areas (English)"
                    name: "areas_en"
                    widget: "list"
                    field: { label: "Area", name: "area", widget: "string" }
                  - label: "Areas (Hebrew)"
                    name: "areas_he"
                    widget: "list"
                    field: { label: "Area", name: "area", widget: "string" }
              - label: "Professional Memberships"
                name: "memberships"
                widget: "object"
                fields:
                  - { label: "Title (English)", name: "title_en", widget: "string", default: "Professional Memberships" }
                  - { label: "Title (Hebrew)", name: "title_he", widget: "string", default: "חברויות מקצועיות" }
                  - label: "Organizations (English)"
                    name: "organizations_en"
                    widget: "list"
                    field: { label: "Organization", name: "organization", widget: "string" }
                  - label: "Organizations (Hebrew)"
                    name: "organizations_he"
                    widget: "list"
                    field: { label: "Organization", name: "organization", widget: "string" }
      - name: "creators-protection"
        label: "Creators Protection"
        file: "content/creators-protection.md"
        fields:
          - { label: "Title (English)", name: "title_en", widget: "string" }
          - { label: "Title (Hebrew)", name: "title_he", widget: "string" }
          - { label: "Description (English)", name: "description_en", widget: "string" }
          - { label: "Description (Hebrew)", name: "description_he", widget: "string" }
          - { label: "Office Vision (English)", name: "officeVision_en", widget: "text" }
          - { label: "Office Vision (Hebrew)", name: "officeVision_he", widget: "text" }
          - label: "Services (English)"
            name: "services_en"
            widget: "list"
            field: { label: "Service", name: "service", widget: "string" }
          - label: "Services (Hebrew)"
            name: "services_he"
            widget: "list"
            field: { label: "Service", name: "service", widget: "string" }
      - name: "users-protection"
        label: "Users Protection"
        file: "content/users-protection.md"
        fields:
          - { label: "Title (English)", name: "title_en", widget: "string" }
          - { label: "Title (Hebrew)", name: "title_he", widget: "string" }
          - { label: "Description (English)", name: "description_en", widget: "string" }
          - { label: "Description (Hebrew)", name: "description_he", widget: "string" }
          - { label: "Office Vision (English)", name: "officeVision_en", widget: "text" }
          - { label: "Office Vision (Hebrew)", name: "officeVision_he", widget: "text" }
          - label: "Services (English)"
            name: "services_en"
            widget: "list"
            field: { label: "Service", name: "service", widget: "string" }
          - label: "Services (Hebrew)"
            name: "services_he"
            widget: "list"
            field: { label: "Service", name: "service", widget: "string" }
      - name: "power-of-attorney"
        label: "Power of Attorney"
        file: "content/power-of-attorney.md"
        fields:
          - { label: "Title (English)", name: "title_en", widget: "string" }
          - { label: "Title (Hebrew)", name: "title_he", widget: "string" }
          - { label: "Description (English)", name: "description_en", widget: "string" }
          - { label: "Description (Hebrew)", name: "description_he", widget: "string" }
          - { label: "Office Vision (English)", name: "officeVision_en", widget: "text" }
          - { label: "Office Vision (Hebrew)", name: "officeVision_he", widget: "text" }
          - label: "Services (English)"
            name: "services_en"
            widget: "list"
            field: { label: "Service", name: "service", widget: "string" }
          - label: "Services (Hebrew)"
            name: "services_he"
            widget: "list"
            field: { label: "Service", name: "service", widget: "string" }
      - name: "contact"
        label: "Contact Page"
        file: "content/contact.md"
        fields:
          - { label: "Title (English)", name: "title_en", widget: "string" }
          - { label: "Title (Hebrew)", name: "title_he", widget: "string" }
          - { label: "Description (English)", name: "description_en", widget: "string" }
          - { label: "Description (Hebrew)", name: "description_he", widget: "string" }
          - { label: "Get In Touch Title (English)", name: "getInTouchTitle_en", widget: "string", default: "Get In Touch" }
          - { label: "Get In Touch Title (Hebrew)", name: "getInTouchTitle_he", widget: "string", default: "צור קשר" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Office Address", name: "officeAddress", widget: "text" }
          - { label: "Office Hours", name: "officeHours", widget: "text" } 